#!/bin/sh


## print with color
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

printf "${GREEN}Verificando por debugs no projeto\n"
printf "${NC}\n"

PASS=true
composer verify


if [ $? -ne 0 ]; then
    PASS=false
fi

if ! $PASS; then
    printf "${RED}Debugs detectados. Corrija antes de fazer commit\n"

    printf "${NC}Se deseja continuar, digite 'y' ou 'Y' para continuar"
    read -r CONTINUAR

    if [ "$CONTINUAR" != "y" ] && [ "$CONTINUAR" != "Y" ]; then
        exit 1
    fi
fi

printf "\n"
printf "${GREEN}Verificando por erros de sintaxe no projeto\n"


# Lista de ficheiros PHP alterados a serem verificados
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep \\.php$)

if [ "$FILES" = "" ]; then
    printf "${NC}Nenhum ficheiro PHP alterado."
    exit 0
fi

# Corre o PHPCS nos ficheiros alterados
PASS=true

printf "${NC}Verificando com PHP CodeSniffer..."

for FILE in $FILES; do
    /usr/bin/phpcs -l -q --colors --warning-severity=0 --ignore=app/helpers.php "$FILE"

    if [ $? -ne 0 ]; then
        PASS=false
    fi
done

if ! $PASS; then
    printf "${RED}PHPCS detectou erros. Corrija antes de fazer commit\n"
    exit 1
fi


printf "\n"

printf "${GREEN}Everithing OK. Pressione enter para continuar\n"
printf "${NC}\n"

read -r CONTINUAR

exit 0
