version: 0.1
cli:
  version: 1.22.2
plugins:
  sources:
    - id: trunk
      ref: v1.6.1
      uri: https://github.com/trunk-io/plugins
runtimes:
  enabled:
    - go@1.21.0
    - node@18.12.1
    - php@>=8.0.0
    - python@3.10.8
tools:
  definitions:
    - name: phpcs
      runtime: php
      package: squizlabs/php_codesniffer
      known_good_version: 3.7.1
      shims: [phpcs]
    - name: phpstan
      runtime: php
      package: phpstan/phpstan
      known_good_version: 1.10.21
      shims: [phpstan]
    - name: phpinsights
      runtime: php
      package: nunomaduro/phpinsights
      known_good_version: 2.10.0
      shims: [phpinsights]
    - name: psalm
      runtime: php
      package: vimeo/psalm
      known_good_version: 5.12.0
      shims: [psalm]
lint:
  definitions:
    - name: phpcs
      description: Keeps PHP code up to standards
      files: [php]
      tools: [phpcs]
      direct_configs: [phpcs.xml, .phpcs.xml, phpcs.xml.dist, .phpcs.xml.dist]
      known_good_version: 3.7.1
      suggest_if: config_present
      version_command:
        parse_regex: phpcs ${semver}
        run: phpcs --version
      commands:
        - name: lint
          run: phpcs ${target}
          output: lsp_json
          batch: true
          read_output_from: tmp_file
          run_from: ${parent}
          success_codes: [0]
          cache_results: true
    - name: phpstan
      description: Keeps PHP code up to standards
      files: [php]
      tools: [phpstan]
      direct_configs: [.neon, phpstan.neon, phpstan.neon.dist]
      known_good_version: 1.10.21
      suggest_if: config_present
      version_command:
        parse_regex: phpstan ${semver}
        run: phpstan --version
      commands:
        - name: lint
          run: phpstan analyse ${target}
          output: lsp_json
          batch: true
          read_output_from: tmp_file
          run_from: ${parent}
          success_codes: [0]
          cache_results: true
    - name: phpinsights
      description: Keeps PHP code up to standards
      files: [php]
      tools: [phpinsights]
      direct_configs: [.json, .phpinsights.php, phpinsights.php]
      known_good_version: 2.10.0
      suggest_if: config_present
      version_command:
        parse_regex: phpinsights ${semver}
        run: phpinsights --version
      commands:
        - name: lint
          run: phpinsights analyse ${target}
          batch: true
          output: lsp_json
          read_output_from: tmp_file
          run_from: ${parent}
          success_codes: [0]
          cache_results: true
    - name: psalm
      description: A static analysis tool for finding errors in PHP applications
      files: [php]
      tools: [psalm]
      direct_configs: [psalm.xml, .psalm.xml, psalm.xml.dist, .psalm.xml.dist]
      known_good_version: 5.12.0
      suggest_if: config_present
      version_command:
        parse_regex: psalm ${semver}
        run: psalm --version
      commands:
        - name: lint
          run: psalm --output-format=emacs ${target}
          output: lsp_json
          batch: true
          read_output_from: tmp_file
          run_from: ${parent}
          success_codes: [0, 2]
          cache_results: true
  enabled:
    - eslint@9.7.0
    - djlint@1.34.1
    - sort-package-json@2.10.0
    - phpinsights@2.10.0
    - phpstan@1.10.58
    - phpcs@3.7.1
    - psalm@5.12.0
    - semgrep@1.79.0
    - stylelint@16.7.0
    - codespell@2.3.0
    - checkov@3.2.191
    - git-diff-check
    - hadolint@2.12.0
    - markdownlint@0.41.0
    - osv-scanner@1.8.2
    - oxipng@9.1.2
    - prettier@3.3.3
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - svgo@3.3.2
    - taplo@0.9.2
    - tflint@0.52.0
    - trivy@0.53.0
    - trufflehog@3.79.0
    - yamllint@1.35.1
actions:
  disabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
  enabled:
    - trunk-upgrade-available
